config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/arctic3d:
      branch: main
      repo: https://github.com/haddocking/arctic3d
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/arctic3d git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-russet-greyhound.sh
        container: qc.acc_tacky-auburn-barracuda
  QC.Doc:
    repos:
      github.com/haddocking/arctic3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cinnabar-worm.sh
        container: qc.doc_scaly-brown-mastiff
      github.com/haddocking/arctic3d git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-khaki-chinook.sh
        container: qc.doc_randy-russet-dragonfly
      github.com/haddocking/arctic3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-chartreuse-walrus.sh
        container: qc.doc_scummy-azure-terrier
      github.com/haddocking/arctic3d restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-crimson-molly.sh
        container: qc.doc_gummy-black-mammoth
  QC.Lic:
    repos:
      github.com/haddocking/arctic3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-wheat-chimpanzee.sh
        container: qc.lic_hazy-chestnut-wasp
  QC.Sec:
    repos:
      github.com/haddocking/arctic3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cornflower-ferret.sh
        container: qc.sec_woozy-vermilion-sheepdog
  QC.Sty:
    repos:
      github.com/haddocking/arctic3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-olive-budgerigar.sh
        container: qc.sty_sleepy-black-warthog
      github.com/haddocking/arctic3d jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-mustard-bee.sh
        container: qc.sty_thirsty-cream-starfish
  QC.Ver:
    repos:
      github.com/haddocking/arctic3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-flax-bordeaux.sh
        container: qc.ver_grumpy-cinnabar-dolphin
timeout: 5400
